### ISSUE TITLE
No longer works on icingaweb2 2.9.1

### ISSUE THREAD

**Issue by rodolfosalgado** [Thomas-Gelf/icingaweb2-module-enforceddashboard#1]
Thomas, I don't know how to code in PHP and your module is really important for me... I wonder if you can fix what is wrong with your module... whenever I try to load that it just says "Page not found"....

**Comment by wferi** [comment]
Unfortunately it fails the same way with 2.6 as well. Is it unreasonable to fix?

**Comment by Thomas-Gelf** [comment]
Page not found should only appear when your user has no permission to access the `enforceddashboard` module

**Comment by Thomas-Gelf** [comment]
Anyways, I'll try to find a solution to work around this issue

**Comment by Thomas-Gelf** [comment]
Should have been fixed with #1
